# Generated by Django 3.1.6 on 2021-02-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
