# Generated by Django 3.1.6 on 2021-02-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helapp', '0002_auto_20210212_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
