# Generated by Django 3.0.5 on 2021-02-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helapp', '0004_auto_20210212_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.TextField(default='name'),
        ),
    ]
