# Generated by Django 3.0.5 on 2021-02-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helapp', '0005_auto_20210213_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.TextField(),
        ),
    ]
