# Generated by Django 3.0.5 on 2021-02-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helapp', '0006_auto_20210213_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.TextField(default='name'),
        ),
    ]
