# Generated by Django 3.1.6 on 2021-02-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helapp', '0007_auto_20210213_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.TextField(),
        ),
    ]
