# Generated by Django 3.1.6 on 2021-02-13 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helapp', '0008_auto_20210213_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
