# Generated by Django 3.1.6 on 2021-02-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helapp', '0009_auto_20210213_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='myuser',
            name='userPhotosText',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
